### ISSUE TITLE
The Json request should be finished

### ISSUE THREAD

**Issue by xpheres** [xpheres/AndroidAnalyticalTranslator#2]
The Json request should be finished.

Code:
https://github.com/xpheres/AndroidAnalyticalTranslator/blob/master/app/src/main/java/com/example/root/analyticaltranslator/MainActivity.java

**Comment by Swati4star** [comment]
http://lingoworld.eu/translator/website/php/translatorfunction.php

What are the names of the put request parameters required by this script?

**Comment by xpheres** [comment]
The source code of all PHP scripts can be found here: https://github.com/xpheres/analyticaltranslator/tree/master/website/php
That script is this: https://github.com/xpheres/analyticaltranslator/blob/master/website/php/translatorfunction.php

**Comment by Swati4star** [comment]
Finishing the JSON Request : [84c9d2b](https://github.com/xpheres/AndroidAnalyticalTranslator/pull/6/commits/84c9d2be7aec163dfce4356c2c69e4c186cce17e)

**Comment by xpheres** [comment]
Thank you! now it is working!

**Comment by xpheres** [comment]
Thanks for again for your help, now half the work is done, to complete the json request I need to request the analysis of the sentences to this script https://github.com/xpheres/analyticaltranslator/blob/master/website/php/messagefunction.php and show the results to the grammar alerts text field. This can be done simultaneosly or an analysis button can be added.

**Comment by Swati4star** [comment]
I suppose this link
http://lingoworld.eu/translator/website/php/messagefunction.php
is the link of API.
I tried making a post request with 7-8 German test cases, but the response is always null.
Help me out in this thing.

**Comment by xpheres** [comment]
That script is intended to report grammar alerts and it only gives a non null response when an implemented grammar mistake is detected. Please try some of the following sentences with purposely mistakes (with false gender / cases): "Die Mann", "Der tochter", "ich gebe den Schwester geld".

**Comment by Swati4star** [comment]
Finishing the JSON Request and reporting the grammar alerts : 	[dacdb18]
(https://github.com/xpheres/AndroidAnalyticalTranslator/pull/9/commits/dacdb1826ab437c603a34f04a3ab49fae2918082)

**Comment by xpheres** [comment]
Amazing! It works like a charm! Now this issue can be closed, the program is fully functional now. Please be aware that a small error was introduced, the API name of the translation script was changed and it won't response untill you restore it: https://github.com/xpheres/AndroidAnalyticalTranslator/commit/8976a93b00dcf4de8a496ed7a0a3793d2893855b
Please make sure you correct it on your fork and thanks very much for your help! :)

**Comment by Swati4star** [comment]
Happy to help! :)
