### ISSUE TITLE
Update versionCode

### ISSUE THREAD

**Issue by krt16s** [xpheres/AndroidAnalyticalTranslator#7]
To release a new version, you have to update the versioncode in `app/build.gradle`, as explained in  as explained in https://developer.android.com/tools/publishing/versioning.html

E.g:

````
        versionCode 2
        versionName "0.02"
````

You also should tag the commit changing the versioncode.

**Comment by xpheres** [comment]
Done: https://github.com/xpheres/AndroidAnalyticalTranslator/blob/master/app/build.gradle

Thank you

**Comment by krt16s** [comment]
Closed by 4d62b1b6b34c8ed9ffb643df3e1890d33fd83174.
